### PR TITLE
Add Emojis

### PR DESCRIPTION
**Pull request by merlindoescode**
Add emojis to headlines

### CODE REVIEW

**Comment by merlindoescode** [comment]
this pull request is a possible solution to issue #18 
pls add pull request on the right side under development. due to write rights i cannot do it

**Comment by merlindoescode** [comment]
found a problem...
it looks like the markdown-content-table link is not working with emojis
i will look into this maybe there is a solution for it

**Comment by merlindoescode** [comment]
ok i tried getting the conent-table to work again but i think it will not work like this...

i tried:

[Audio Editors](# 🎛️ Audio-Editors 🎛️ )

[Audio Editors](#🎛️-Audio-Editors-🎛️)

<a name="🎛️ Audio Editors 🎛️">
   🎛️ Audio Editors 🎛️
</a>

<a name="🎛️-Audio Editors-🎛️">
   🎛️ Audio Editors 🎛️
</a>

<a name=":control_knobs: Audio Editors :control_knobs:">
   :control_knobs: Audio Editors :control_knobs:
</a>

maybe it should not be...
if someone else has an idea pls let me know. i will test it

**Comment by sereneblue** [comment]
@merlindoescode, thanks for contributing but I don't see much value in adding emojis.

**Pull request closed without merging**
