### PR TITLE
add quick capture

### PR DESCRIPTION
**Pull request by minthemiddle**
Add Quick Capture:
A quick capture app for adding thoughts to a daily markdown note.  

Fully open source, cross-platform.

Added to "Other" as no text editor, just a text capturer.

### CODE REVIEW

**Comment by sereneblue** [comment]
Hi @minthemiddle,

Thank you for contributing but this awesome list is geared towards projects with more traction.

**Comment by minthemiddle** [comment]
Hi @sereneblue, your repo, your rules. Would have been helpful to know this before doing the work and getting the disappointment.

**Comment by sereneblue** [comment]
> Hi @sereneblue, your repo, your rules. Would have been helpful to know this before doing the work and getting the disappointment. You might consider adding this to your contribution guidelines. Also, feedback from open source developer perspective: Traction comes from being visible, so it's a hen egg problem.
> 
> Anyway, no hard feelings, don't feel obliged to even answer.

Thanks, I will update the issue template to address this.

**Comment by sereneblue** [comment]
> Hi @sereneblue, your repo, your rules. Would have been helpful to know this before doing the work and getting the disappointment. You might consider adding this to your contribution guidelines. Also, feedback from open source developer perspective: Traction comes from being visible, so it's a hen egg problem.
> 
> Anyway, no hard feelings, don't feel obliged to even answer.

Thanks, I will add a guideline for contributing.

**Pull request closed without merging**
